### ISSUE TITLE
runner.py 运行报错

### ISSUE THREAD

**Issue by Archer456** [Louis-me/appium#3]
![default](https://user-images.githubusercontent.com/18392901/34709810-c3a03ac0-f553-11e7-8c67-ab6a69dad36a.png)
pycharm 运行runner.py   
看日志 应该是 项目里没有打包Log目录 ，本地创建报错了。。。

**Comment by Archer456** [comment]
cmd@TR:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
cmd@TR:~$ appium -v
1.7.1
cmd@TR:~$ python3 -V
Python 3.6.3

**Comment by Archer456** [comment]
我自己到 ../appium/  下 创建Log 后执行通过了。


cmd@TR:~$ adb devices -l
List of devices attached
192.168.58.101:5555    device product:vbox86p model:Google_Nexus_9___7_1_0___API_25___1536x2048 device:vbox86p

但报了以下错误：
`/usr/bin/python3.5 /home/cmd/workspace/git/appium/runner/runner.py
------read-------
{}
---write------
appium --session-override  -p 4773 -bp 4746 -U 192.168.58.101:5555
Success
Success
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
---------start_server----------
----server_ 成功---
----runnerPool------
{'devices': '192.168.58.101:5555', 'port': '4773', 'bport': '4746'}
adb -s 192.168.58.101:5555 shell cat /system/build.prop 
{'release': '7.1.1', 'device': 'device1', 'brand': 'brand1', 'model': 'model2'}
--------- countDate------
ERROR
------read-------

{'versionCode': '35', 'sum': 0, 'packingTime': '2017/11/21 09:00', 'fail': 0, 'versionName': '1.3.5', 'pass': 0}
======================================================================
{'versionCode': '35', 'sum': 0, 'packingTime': '2017/11/21 09:00', 'fail': 0, 'versionName': '1.3.5', 'pass': 0}
ERROR: setUpClass (testcase.HomeTest.HomeTest)
---write------
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cmd/workspace/git/appium/testcase/HomeTest.py", line 162, in setUpClass
    super(HomeTest, cls).setUpClass()
  File "/home/cmd/workspace/git/appium/Base/BaseRunner.py", line 60, in setUpClass
    cls.driver = appium_testcase(devices)
  File "/home/cmd/workspace/git/appium/Base/BaseRunner.py", line 43, in appium_testcase
    driver = webdriver.Remote(remote, desired_caps)
  File "/home/cmd/.local/lib/python3.5/site-packages/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/home/cmd/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/cmd/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/cmd/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/home/cmd/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity


----------------------------------------------------------------------
Ran 0 tests in 14.133s

FAILED (errors=1)
------read-------
{'versionCode': '35', 'fail': 0, 'packingTime': '2017/11/21 09:00', 'testDate': '2018-01-09 15:48:16', 'sum': 0, 'testSumDate': '14秒', 'versionName': '1.3.5', 'pass': 0}
------read-------
[]
Traceback (most recent call last):
  File "/home/cmd/workspace/git/appium/runner/runner.py", line 102, in <module>
    writeExcel()
  File "/home/cmd/workspace/git/appium/Base/BaseStatistics.py", line 105, in writeExcel
    operateReport.close()
  File "/home/cmd/workspace/git/appium/Base/BaseExcel.py", line 131, in close
    self.wd.close()
  File "/usr/lib/python3/dist-packages/xlsxwriter/workbook.py", line 295, in close
    self._store_workbook()
  File "/usr/lib/python3/dist-packages/xlsxwriter/workbook.py", line 524, in _store_workbook
    allowZip64=self.allow_zip64)
  File "/usr/lib/python3.5/zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cmd/workspace/git/appium/Report/Report.xlsx'

Process finished with exit code 1
`

**Comment by Archer456** [comment]
Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

还是那个issue   项目里没有那个  com.huawei.works  这个能打包进去吗  我想先看下执行效果

**Comment by Archer456** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/cmd/workspace/git/appium/Report/Report.xlsx'
还有这个错误  是你项目里打包  我看了下 本地的是小写的 report目录。。。
本地改为大写Report。。。

**Comment by Louis-me** [comment]
嗯，代码在这台电脑上没有怎么测试。。。修改过来了，再试试
