### ISSUE TITLE
[UiAutomator2] Unable to remove port forward 'Error executing adbExec.

### ISSUE THREAD

**Issue by Morrison-Yang** [Louis-me/appium#9]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'F\:\\install\\sdk\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s devicesname forward --remove tcp\:4734' exited with code 1'; Stderr: 'error: listener 'tcp:4734' not found'; Code: '1''
[HTTP] <-- POST /wd/hub/session 500 8952 ms - 187 
[MJSONWP] Encountered internal error running command: TypeError: Cannot create property 'replace' on boolean 'true'
    at ADB.callee$0$0$ (../../../lib/tools/apk-utils.js:331:20)
    at tryCatch (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at invoke (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:136:37)
    at enqueueResult (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (F:\install\nodejs\node_cache\node_modules\_core-js@1.2.7@core-js\library\modules\$.export.js:30:36)
    at AsyncIterator.enqueue (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at Object.runtime.async (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:209:12)
    at ADB.callee$0$0 [as install] (../../../lib/tools/apk-utils.js:356:23)
    at UiAutomator2Server.signAndInstall$ (../../lib/uiautomator2.js:109:20)
    at tryCatch (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (F:\install\nodejs\node_cache\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
--------- countDate------
ERROR
------read-------

{'versionCode': '40', 'versionName': '1.4.0', 'packingTime': '2017/12/4 13:00', 'sum': 0, 'pass': 0, 'fail': 0}
======================================================================
{'versionCode': '40', 'versionName': '1.4.0', 'packingTime': '2017/12/4 13:00', 'sum': 0, 'pass': 0, 'fail': 0}
ERROR: setUpClass (TestCase.CardsTest.CardsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "G:\Python_project\appium\TestCase\CardsTest.py", line 43, in setUpClass
    super(CardsTest, cls).setUpClass()
  File "G:\Python_project\appium\Base\BaseRunner.py", line 63, in setUpClass
    cls.driver = appium_testcase(devicess)
  File "G:\Python_project\appium\Base\BaseRunner.py", line 46, in appium_testcase
    driver = webdriver.Remote(remote, desired_caps)
  File "F:\install\Miniconda3\envs\py36\lib\site-packages\appium_python_client-0.26-py3.6.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "F:\install\Miniconda3\envs\py36\lib\site-packages\selenium-3.9.0-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "F:\install\Miniconda3\envs\py36\lib\site-packages\selenium-3.9.0-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "F:\install\Miniconda3\envs\py36\lib\site-packages\selenium-3.9.0-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "F:\install\Miniconda3\envs\py36\lib\site-packages\selenium-3.9.0-py3.6.egg\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot create property 'replace' on boolean 'true'

----------------------------------------------------------------------
Ran 0 tests in 9.407s

FAILED (errors=1)

**Comment by Morrison-Yang** [comment]
appium 版本 1.7.2

**Comment by Morrison-Yang** [comment]
注释掉runner.py跟BaseRunner.py下的_initApp["automationName"] = "uiautomator2"跟desired_caps["automationName"] = devices['automationName']，该问题即可解决
